export const bggTop100 = [
    { name: '7 Wonders', weight: 2.4 },
    { name: 'Agricola', weight: 3.5 },
    { name: 'A Feast for Odin', weight: 3.94 },
    { name: 'Ark Nova', weight: 3.71 },
    { name: 'Azul', weight: 1.8 },
    { name: 'Bingo', weight: 0.2 },
    { name: 'Blood Rage', weight: 3.1 },
    { name: 'Brass: Birmingham', weight: 3.9 },
    { name: 'Carcassonne', weight: 1.9 },
    { name: 'Caverna: The Cave Farmers', weight: 3.1 },
    { name: 'Clank!: A Deck-Building Adventure', weight: 2.5 },
    { name: 'Codenames', weight: 1.8 },
    { name: 'Dominion', weight: 2.0 },
    { name: 'Dune: Imperium', weight: 3.01 },
    { name: 'Everdell', weight: 2.7 },
    { name: 'Gaia Project', weight: 4.39 },
    { name: 'Gloomhaven', weight: 3.89 },
    { name: 'Gloomhaven: Jaws of the Lion', weight: 3.62 },
    { name: 'Great Western Trail', weight: 3.7 },
    { name: 'King of Tokyo', weight: 1.8 },
    { name: 'Lost Ruins of Arnak', weight: 2.65 },
    { name: 'Nemesis', weight: 3.5 },
    { name: 'Pandemic', weight: 2.0 },
    { name: 'Pandemic Legacy: Season 1', weight: 2.83 },
    { name: 'Patchwork', weight: 1.6 },
    { name: 'Power Grid', weight: 3.2 },
    { name: 'Puerto Rico', weight: 2.9 },
    { name: 'Quacks', weight: 1.94 },
    { name: 'Scythe', weight: 3.44 },
    { name: 'Seven Wonders Duel', weight: 2.8 },
    { name: 'Spirit Island', weight: 4.06 },
    { name: 'Splendor', weight: 1.9 },
    { name: 'Star Wars: Rebellion', weight: 3.73 },
    { name: 'Terraforming Mars', weight: 3.26 },
    { name: 'The Castles of Burgundy', weight: 2.99 },
    { name: 'Through the Ages: A New Story of Civilization', weight: 4.43 },
    { name: 'Ticket to Ride', weight: 2.3 },
    { name: 'Twilight Imperium: Fourth Edition', weight: 4.3 },
    { name: 'Twilight Struggle', weight: 3.6 },
    { name: 'Uno', weight: 1.1 },
    { name: 'Virgin Queen', weight: 4.44 },
    { name: 'War of the Ring: Second Edition', weight: 4.2 },
    { name: 'Wingspan', weight: 2.4 },
    { name: 'Zombicide', weight: 2.5 },
];
